### ISSUE TITLE
Install and setup instructions for the WireGuard VPN Server

### ISSUE THREAD

**Issue by bsorescu** [pi-hosted/pi-hosted#1]
**Question**
Hi there, i have the following issue:
Install and setup instructions for the WireGuard VPN Server as described in the wireguard-install.md readme file.

**Context**

I'm running everything on a Raspberry Pi 4.
Whenever I try to click on "Copy as custom" i get the following error:

"**Failure
json: cannot unmarshal bool into Go struct field TemplateEnv.Templates.env.default of type string"**

However this doesn't happen when I simply deploy the stack without trying to change any settings.

**Comment by blumberg** [comment]
Currently, there is a bug where we can´t click on `Copy as custom` for some reason. I've tried to understand why but still haven't found how to solve it.

Meanwhile, you can copy the `docker-compose` file straight from [stack/wireguard-easy.yml](https://github.com/pi-hosted/pi-hosted/blob/master/stack/wireguard-easy.yml). Take a look at [this other documentation](https://github.com/pi-hosted/pi-hosted/blob/master/docs/photoprism.md#creating-a-custom-stack-manually) as a reference if you need it.

**Comment by rmiddle** [comment]
This is something I need to work on.  I have been meaning to update the app template and documentation on this one.
