### ISSUE TITLE
[REQUEST] NordVPN Template

### ISSUE THREAD

**Issue by shalk3** [pi-hosted/pi-hosted#10]
Hi,

Is there any chance you can add a template for NordVPN (https://hub.docker.com/r/azinchen/nordvpn) ? I've tried all day to get it to work... unfortunetly no success.  

Kindly appreciated!

**Comment by rmiddle** [comment]
It likely requires extra permissions.

**Comment by xoste49** [comment]
install raspberry os 64 bit and then it should work
