### ISSUE TITLE
WG_DEFAULT_ADDRESS instructions missing within the Install guide

### ISSUE THREAD

**Issue by iCSpotRun** [pi-hosted/pi-hosted#101]
**Question**
When setting all the variables, the WG_DEFAULT_ADDRESS instructions is missing within the install guide. Can this be added please? I am undeniable to get this working and I think it's because I do not know how to set this variable.

https://github.com/pi-hosted/pi-hosted/blob/master/docs/wireguard-install.md

<img width="667" alt="Screen Shot 2022-10-23 at 11 45 06 AM" src="https://user-images.githubusercontent.com/6014317/197407420-1a9be375-9125-45d4-9e64-a0ad59700ed6.png">

**Comment by henkiewie** [comment]
I tested this; should leave the '10.8.0.x' as is then it will automatically adjust the wg0.conf to the right value for the WG server starting at `10.8.0.1/32` and iptables subnet to `10.8.0.0/24` You're right it's not in the manual. The first client got `10.8.0.2/32` etc. Maybe it's also good to add;
If you use wireguard in combination with the docker pihole template, change the pihole default setting from `Respond only on interface eth0` to `Permit all origins` if not you will not be able to use the pihole address as your DNS in Wireguard.

**Comment by rmiddle** [comment]
Doc updated.  Closing.
