### ISSUE TITLE
[REQUEST] PodRacer

### ISSUE THREAD

**Issue by itsdoublearon** [pi-hosted/pi-hosted#121]
Thanks to everyone who has worked so hard to keep this project going. 

I'm fairly new to all over this, but I would like to request and see if there is anyway to get the application PodRacer supported for deployment in Docker with this project please.

Here's the project I'm referring to.. https://github.com/ZNielsen/PodRacer

Thanks so much.

**Comment by rmiddle** [comment]
I don't see an existing docker instance for it, so someone would need to create a docker image before we could add it to the template.

**Comment by Macleykun** [comment]
https://github.com/ZNielsen/PodRacer/issues/51
Working on it, but sadly the compiler panicked.

It'll probably be smth very short so easy to write:
```
docker pull rust:slim
get the files
apt install pkg-config libssl-dev
rustup override set nightly && rustup update && cargo update && cargo build --release
cargo run --release --bin podracer
```

**Comment by itsdoublearon** [comment]
Awesome, thanks so much. I followed the other thread and it looks like you're getting close?

**Comment by Macleykun** [comment]
> Awesome, thanks so much. I followed the other thread and it looks like you're getting close?

yup, we had some issues related to the compiler, i'll have a look at it sometime so people can use it with docker and then i can add it here to resolve your request

**Comment by Macleykun** [comment]
we finnaly have a docker image :D 
docker run -d -v podracer_podcasts:/app/podcasts/ -p 41968:41968/tcp --name podracer ghcr.io/znielsen/podracer:latest
Now we gotta template this and it should be good to go.

**Comment by itsdoublearon** [comment]
Loaded up fine, but in testing trying to create a podcast feed...

Synology: 500 Internal Server Error
RPi Zero 2: Stuck in a loop with CPU Maxed out, after five minutes times out in browser
VPS Ubuntu 1GB Ram: Stuck in a loop with CPU Maxed out

**Comment by ZNielsen** [comment]
Fixed the stuck in a loop bug, new container is building now.

**Comment by itsdoublearon** [comment]
SUCCESS!!! Thanks so much everyone for your hard work, really appreciate it.

**Comment by Macleykun** [comment]
great to hear :) enjoy
