### ISSUE TITLE
Import the repository instead of using a fork

### ISSUE THREAD

**Issue by ryanfortner** [pi-hosted/pi-hosted#13]
@novaspirit @rmiddle using an organization is a good idea for this project, I agree with your decision to make one. But having a fork as the main repository doesn't seem right. Instead of using a fork, you can actually import the novaspirit/pi-hosted repository. Click the + on the top right hand corner, click import repository. 
![image](https://user-images.githubusercontent.com/71036629/161170332-8997ecb8-ca76-456b-8ddf-52f02fb9bb66.png)
Put https://github.com/novaspirit/pi-hosted as the repository you want to import, and choose the correct pi-hosted organization. Doing this will not only redirect people from the old to the new one, but it will also keep the amount of stargazers/contributors/forks the same.

Also, I think the project would benefit from having a better website and even a documentation site. I'd be willing to help with both of these things, for example something like https://docs.raspbian-addons.org , what do you think?

**Comment by rmiddle** [comment]
Would importing the repo allow existing links to novaspriit/pi-hosted repository to keep working?

**Comment by ryanfortner** [comment]
> Would importing the repo allow existing links to novaspriit/pi-hosted repository to keep working?

It would migrate everything from that repository over to this one. Users would get automatically redirected to this one. I think the old nova spirit/pi-hosted will be removed.

**Comment by blumberg** [comment]
After importing I believe the old one would be removed, but then you can fork it back so links would return to work. Doing so pi-hosted/pi-hosted becomes master and novaspirit/pi-hosted becomes a fork.

**Comment by paulwratt** [comment]
actually this is really important, if for some reason @novaspirit were unable to administer PR's and Issues, then the other members of the "pi-hosted" organisation dont have to "change anything" in order for the project to continue ticking along.

As a bonus, espcially while testing or needing specific settings (private settings), @novaspirit can use branches on their own fork, that _dont_ have to be present on the "pi-hosted" repo ..

"never say never"

**Comment by rmiddle** [comment]
Something we want to do at some point, but not ready yet.
