### ISSUE TITLE
[REQUEST] Pi-Hole and DHCP

### ISSUE THREAD

**Issue by BenSeventy9** [pi-hosted/pi-hosted#131]
If you run DHCP server in Pi-Hole you need to add `NET_ADMIN` capabilities and use `host` network.
This is not covered in the docs and verry frustrating research.

Create seperate DHCP documentation

More advanced solution: https://ilyess.cc/posts/pihole-dhcp-docker-bridge-network

> Running Pihole on Docker is pretty straightforward, but things start to get a bit complicated when it comes to enabling DHCP - using Pihole to serve DHCP requests. With Docker’s default bridge network mode, we can’t use Pihole as a DHCP server. So we have two options: (1) use the host network mode, or (2) run a DHCP relay (more on this later).

> Option (1) is the easiest because all we’d have to do is set network_mode: "host" in the service definition, but it comes with a considerable disadvantage. It undermines the network isolation provided by Docker’s bridge driver, not to mention that it will take up ports from the host’s network which could be a concern depending on what’s running on your server. Option (2) allows us to stick to the bridge mode but adds a good amount of complexity. If you’re anything like me, you’ll favour security and try to maintain Docker’s network isolation.

**Comment by Macleykun** [comment]
I do agree that this should be more upfront, we can edit the description to also include this. Suggest to enable Host adapter if they plan to use the DHCP (after the message reads to follow the article about binding ports).

By default, i don't think it's handy to assign the host network, as users probably will get issues if they don't use the dhcp. They can easily change that luckily so i assume this part is fine.

The capabilities is something i had to tweak aswell with the pixel-server, but the only way to facilitate this is by running it with privileged (which is bad practice admittedly). So this also can't be set by default. Users can however edit this by themselfs by opening advance options and adding it almost at the bottom of the deploy section.

> When the installation is complete, navigate to your.ip.goes.here:1010/admin. Follow the article [here](https://medium.com/@niktrix/getting-rid-of-systemd-resolved-consuming-port-53-605f0234f32f) if you run into issues binding to port 53.

to

> When the installation is complete, navigate to your.ip.goes.here:1010/admin. Follow the article [here](https://medium.com/@niktrix/getting-rid-of-systemd-resolved-consuming-port-53-605f0234f32f) if you run into issues binding to port 53. Once you've done so, change the Network type to host and open advance options and scroll to Labels and add: NET_ADMIN with the value True.

Is that correct @BenSeventy9 and what do you think @rmiddle ? I can submit the PR :P

**Comment by BenSeventy9** [comment]
I would change it from
> When the installation is complete, navigate to your.ip.goes.[here](https://medium.com/@niktrix/getting-rid-of-systemd-resolved-consuming-port-53-605f0234f32f):1010/admin. Follow the article here if you run into issues binding to port 53.

to
> When the installation is complete, navigate to your.ip.goes.[here](https://medium.com/@niktrix/getting-rid-of-systemd-resolved-consuming-port-53-605f0234f32f):1010/admin. Follow the article here if you run into issues binding to port 53. If you would like to use Pi-Hole's built in DHCP-Server change the Network type to host and open advance options and scroll to Labels and add: NET_ADMIN with the value True.
