### ISSUE TITLE
[REQUEST] Add UID/GID options to JDownloader

### ISSUE THREAD

**Issue by HowellBP** [pi-hosted/pi-hosted#138]
**Is your feature request related to a problem? Please describe.**
JDownloader has no default UID/GID set, so files downloaded always end up owned by root on the host filesystem.

**Describe the solution you'd like**
Add either a default UID/GID (1000:1000) or add boxes to customize the UID and GID.

**Describe alternatives you've considered**
I manually `chown -R` everything that gets downloaded.

**Comment by Macleykun** [comment]
What about this env var
https://github.com/jaymoulin/docker-jdownloader#:~:text=downloads%20folder%20volume!-,umask%3D%220002%22,-Defines%20specific%20rights
We can basically set that, running under a different user is also possible, but more work.

**Comment by Macleykun** [comment]
Ya could set the env var yourself:
UMASK="0666" but i can't really do this well as we use json and i can't just configure this easily.
Might look into seeing how to run this with using:
https://github.com/jaymoulin/docker-jdownloader#:~:text=your%20download%20mountpoint)-,%2Du%20%3CUID%3E%3A%3CGID%3E,-Add%20user%20identifiers
Which involved not passing a env var, but rather a seperate function.
And this is apparently not supported by portainer either, so you either have to set the env var yourself.
Or request the developer to not use double quotes in the env var or support the uid/gid as env vars.
