### ISSUE TITLE
[QUESTION] Network issue after failed Nginx Proxy Manager installation

### ISSUE THREAD

**Issue by idoodler** [pi-hosted/pi-hosted#140]
**Question**
I wanted to setup Nginx Proxy Manager but it failed. Since then I am having network issues in my containers. How to fix that again?

**Context**
Here are the errors I get:
- Nextcloud
    - `Could not resolve host: www.nextcloud.com`
- Portainer (Can't load App Template)
    - `Get "https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/template/portainer-v2-arm64.json": dial tcp: lookup raw.githubusercontent.com on 192.168.0.20:53: read udp 172.17.0.2:57797->192.168.0.20:53: i/o timeout`

Note: I also setup AdGuardHome, which is disabled now, just to make sure

**Edit:**
I just tried to ping a domain within the nextcloud container and it can't resolve the host

**Comment by Macleykun** [comment]
> **Question** I wanted to setup Nginx Proxy Manager but it failed. Since then I am having network issues in my containers. How to fix that again?
> 
> **Context** Here are the errors I get:
> 
> * Nextcloud
>   
>   * `Could not resolve host: www.nextcloud.com`
> * Portainer (Can't load App Template)
>   
>   * `Get "https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/template/portainer-v2-arm64.json": dial tcp: lookup raw.githubusercontent.com on 192.168.0.20:53: read udp 172.17.0.2:57797->192.168.0.20:53: i/o timeout`
> 
> Note: I also setup AdGuardHome, which is disabled now, just to make sure
> 
> **Edit:** I just tried to ping a domain within the nextcloud container and it can't resolve the host

Strange, this person has the same issue: https://github.com/novaspirit/pi-hosted/issues/418
I also had some issues with containers, could you recreate the portainer container? (i mean stopping it, removing the container and deploy it again).

You can do the same for AdguardHome, your configs/settings should be saved in the volumes (which you don't have to delete!)

**Comment by idoodler** [comment]
Yes, that was it. I did the following steps:

- Stopped and removed the AdGuardHome Container -> No Luck
- Stopped, removed Portainer, Rebooted my system cause it couldn't resolve a domain and executed  `install_portainer.sh` -> Works!

**Comment by idoodler** [comment]
It worked after removing AdGuardHome as a DNS server from my router. The issue and the solution is described here is described here:

https://unix.stackexchange.com/questions/647996/docker-container-dns-not-working-with-pihole/650346#650346?newreg=f5cc2acd94974fb1b5c9ac200417c1ed
