### ISSUE TITLE
Update portainer script not working

### ISSUE THREAD

**Issue by Clubeddie** [pi-hosted/pi-hosted#151]
First of all, thank you for all the great work. I am learning a lot from this config and have nice tools to play with.
Now, the issue. I wanted to update my portainer. so i first sudo-apt-update & upgrade my rp4. 
I did a gitt pull on the pi-hosted directory and 
And when i started the script sh ./update_portainer.sh

i get:
./update_portainer.sh: 3: Syntax error: "(" unexpected

The first 5 lines of the script are:
```
#!/bin/bash

function error() {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}
```
And that seems to be normal. Anyone any clue?

**Comment by martadinata666** [comment]
don't use `sh`, only `update-portainer.sh

**Comment by Clubeddie** [comment]
Feeling extremely stupid right now. That did the trick
