### ISSUE TITLE
[QUESTION] Nextcloud stack installation

### ISSUE THREAD

**Issue by piyushaswani55** [pi-hosted/pi-hosted#152]
**Question**
I am trying nextcloud stack installation but not able to connect to the DB during first run while creating admin user I keep getting this error. Tried every possible thing but it doesn't work for me.

`Error while trying to create admin user: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'nextcloud'@'nextcloud.nextcloud_default' (using password: YES)
`
Even the nextcloudpi is having some trouble, it works fine for the first time but after that when i restart the container, it goes into maintenance mode and then everything goes haywire. 

**Context**
<img width="331" alt="image" src="https://user-images.githubusercontent.com/5944859/226695306-0d67227d-ad91-4424-a2b2-6ca0f051f77f.png">

**Comment by FilmForge3D** [comment]
I have the same exact issue and am looking for a solution, nothing so far
