### ISSUE TITLE
Pi-Hole-Unbound / Request failed with status code 500

### ISSUE THREAD

**Issue by broomwalker** [pi-hosted/pi-hosted#156]
Hi, fantastic work with your App Templates. Makes life easier!

I’ve installed Pi-Hole-Unbound multiple times on my Rasp Pi 4B 8GB and I’ve just tried installing on my Ubuntu Server VM running off Proxmox and I’m getting “Request failed with status code 500” error.

Any suggestions on how to fix? The container is stuck in a state of “created”.

Thanks

**Comment by bossman7309** [comment]
These may help you out but feel free to ask on our discord 

[](https://github.com/pi-hosted/pi-hosted/blob/master/docs/pi-hole.md)

[](https://medium.com/@niktrix/getting-rid-of-systemd-resolved-consuming-port-53-605f0234f32f) this most likely is the problem
