### ISSUE TITLE
Heimdal dont work anymore, i think its need a update.

### ISSUE THREAD

**Issue by StianNOR** [pi-hosted/pi-hosted#157]
**Question**
Error deploying the img something is off.

**Context**
Maybe its not been updated?

**Comment by rmiddle** [comment]
Are you on arm32, arm64, amd64?

**Comment by StianNOR** [comment]
Arm32

**Comment by rmiddle** [comment]
https://www.linuxserver.io/blog/a-farewell-to-arm-hf

Arm32 support is going away for that product.  Over 75 arm32 items are about to go away from our list.  Will be gone in the next few days.
