### ISSUE TITLE
[QUESTION] Setup of admin account on Nextcloud stack fails

### ISSUE THREAD

**Issue by FilmForge3D** [pi-hosted/pi-hosted#160]
**Question**
The setup of the admin account for the Nextcloud stack installation fails due to a database issue. 

`Error while trying to create admin user: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'nextcloud'@'nextcloud.nextcloud_default' (using password: YES)`

The problem occurs with an unmodified installation with only the open variables filled in.

**Context**
[Issue 152](https://github.com/pi-hosted/pi-hosted/issues/152) has the same problem and was left unresolved.

**Comment by ciutadellla** [comment]
Same here
