### ISSUE TITLE
[QUESTION] 2 files with same name "template/portainer-v2-amd64.json" with different file size

### ISSUE THREAD

**Issue by t-philip** [pi-hosted/pi-hosted#176]
Hello Team,

I am new to pi-hosted and sort of a beginner with GIT. I am confused about the following, could one of you please check and confirm?

Under the folder: [Template](https://github.com/pi-hosted/pi-hosted/tree/master/template) I see 2 files with the same name "portainer-v2-amd64.json"

When I go into each of the files with the same name, I see both have different number of contributors and the stats are different. 
May I know why this is so? 

- https://github.com/pi-hosted/pi-hosted/blob/master/template/portainer-v2-amd64.json
9556 lines (9556 loc) · 364 KB

- https://github.com/pi-hosted/pi-hosted/blob/master/template/portainer-v2-arm64.json
9637 lines (9637 loc) · 366 KB

![2023-11-20 16_06_29-pi-hosted_template at master · pi-hosted_pi-hosted - Brave](https://github.com/pi-hosted/pi-hosted/assets/57439211/4546ff04-a4ef-4a35-b578-0e0c38367d36)

Regards,
T. Philip

**Comment by martadinata666** [comment]
amd64 arm64

**Comment by t-philip** [comment]
Sharp eyes, thank you.
