### ISSUE TITLE
The Template Shows blank IP when installing due to the empty config files 

### ISSUE THREAD

**Issue by THELASTOFUS** [pi-hosted/pi-hosted#184]
Just wanted to let you know I noticed your template constantly kept unassigning the IP address despite me running the pre-install script that creates blanks under the /portainer directory.

This causes the logs to error constantly on there being no configuration file (because it's empty even though the 0KB file exists).

Once I replaced with the Traefik.toml/yml sample file 

**# Configuration sample for Traefik v2.**

I was able to keep the TRAEFIK open and also the IP wouldn't disappear!

Please fix this for newbies...cost me hours ....

**Comment by HammyHavoc** [comment]
Yep, have wasted a day on this and still not up and running.
