### ISSUE TITLE
[Bug] CPU Usage metric not showing on RPI docker monitor

### ISSUE THREAD

**Issue by jjak0b** [pi-hosted/pi-hosted#185]
I followed the [guide](https://github.com/pi-hosted/pi-hosted/blob/master/docs/rpi_docker_monitor.md) on Raspberry pi 4 on a new Rasberry pi OS based on Debian 12 Bookworm installation and the dashboard doesn't show the CPU usage.
 i suppose they are related to the c-group options (`systemd.unified_cgroup_hierarchy=0 cgroup_enable=memory cgroup_memory=1`) because all graphs are working except for the CPU Usage one.
 
![image](https://github.com/pi-hosted/pi-hosted/assets/32840785/ef4032b2-ca63-438c-9071-3be00fd768bb)

I'm not the only one who is experiencing this [issue](https://github.com/oijkn/Docker-Raspberry-PI-Monitoring/issues/30) since i followed the guide on a new clean install.

**Comment by drphero** [comment]
Something is definitely wrong with the settings. From #142 I was able to find that `100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[$interval])) * 100)` seems to work for CPU Usage. But then that shows a different number than CPU Busy? Also disk usage and temp show nothing for me.

**Comment by drphero** [comment]
And the sizing is all messed up for mine as well. 
![Screenshot 2023-12-28 at 22-49-46 Docker and OS Metrics for Raspberry Pi 15120 - Dashboards - Grafana](https://github.com/pi-hosted/pi-hosted/assets/14174687/079b58e8-bb33-44e3-b567-6fb1148a07e5)
