### ISSUE TITLE
Nextcloud doens't use the mariadb when deployed

### ISSUE THREAD

**Issue by roely15mol** [pi-hosted/pi-hosted#191]
What is wrong with my nextcloud, it does not use the mariadb?

![image](https://github.com/pi-hosted/pi-hosted/assets/58187423/77935dbd-2c7a-4132-9942-422e084e8b45)

**Comment by dng-sitrep** [comment]
I have the same issue

Initializing nextcloud 28.0.1.1 (this can take a while) ...
Setting permissions
New nextcloud instance
Please run the web-based installer on first connect!
Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Exception: Not installed in /app/www/public/lib/base.php:283

Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
