### ISSUE TITLE
[QUESTION] Authentik Stack default password

### ISSUE THREAD

**Issue by norbsss** [pi-hosted/pi-hosted#197]
**Question**
I have deployed the Authenitk Stack but I don't have the default password and in the deployment process I don't have that env to set up. Any idea what the pass is?

**Comment by CJ0206** [comment]
Have you looked at https://docs.goauthentik.io/docs/installation/docker-compose


> To start the initial setup, navigate to `http://<your server's IP or hostname>:9000/if/flow/initial-setup/`.
> 
> There you are prompted to set a password for the `akadmin` user (the default user).
