### ISSUE TITLE
ReactiveResume deployment error "[FATAL tini (7)] exec supervisord failed: No such file or directory"

### ISSUE THREAD

**Issue by ash-wfhgh** [pi-hosted/pi-hosted#199]
ISSUE:
After running the pre-installation script and deploying the stack, the APP container does no start and is stuck in a loop returning error "[FATAL tini (7)] exec supervisord failed: No such file or directory".

DETAILS:
Checked the logs for both the db & app containers: the db container started normal (without issue), however the app container tries to start but is in an endless loop returning error the listed error message.

Any thought or ideas as what is the issue??  Any help is appreciated.

**Comment by Izaic** [comment]
Having the same issue
