### ISSUE TITLE
Portainer latest has issue showing exec console - need update to 2.20.3

### ISSUE THREAD

**Issue by Strobeener** [pi-hosted/pi-hosted#214]
There is a bug in Docker 26 that when using Portianer 2.19 or earlier doesn't allow exec console to work.  you get "unable to retrieve image details.  There appears to be a fix going to 2.20.3 for Portainer, but it isn't set as "latest".  The install scripts for pi-hosted only pull the "latest".    Need a fix to hard set 2.20.3 during pull.

re: https://github.com/portainer/portainer/issues/11436

**Comment by werefkin** [comment]
> There is a bug in Docker 26 that when using Portianer 2.19 or earlier doesn't allow exec console to work. you get "unable to retrieve image details. There appears to be a fix going to 2.20.3 for Portainer, but it isn't set as "latest". The install scripts for pi-hosted only pull the "latest". Need a fix to hard set 2.20.3 during pull.
> 
> re: [portainer/portainer#11436](https://github.com/portainer/portainer/issues/11436)

Yes, I have also discovered this recently and was checking the current version. The update is apparently needed.

**Comment by Strobeener** [comment]
I modified the installation sequence and was able to fix the issue:   Here is a quick guide for getting it started from fresh:
Prelimsudo apt update && sudo apt upgrade -y
sudo apt install curl
Dockercurl -sSL https://get.docker.com |sh
Portainer (fixes exec console - don't use latest ....yet)sudo docker pull portainer/portainer-ce:2.20.3sudo docker run -d -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:2.20.3

    On Saturday, August 3, 2024 at 06:07:57 AM EDT, werefkin ***@***.***> wrote:  
 
 



There is a bug in Docker 26 that when using Portianer 2.19 or earlier doesn't allow exec console to work. you get "unable to retrieve image details. There appears to be a fix going to 2.20.3 for Portainer, but it isn't set as "latest". The install scripts for pi-hosted only pull the "latest". Need a fix to hard set 2.20.3 during pull.

re: portainer/portainer#11436


Yes, I have also discovered this recently and was checking the current version. The update is apparently needed.

**Comment by werefkin** [comment]
Thanks @Strobeener, looks promising
i will test it when i have time

**Comment by werefkin** [comment]
> I modified the installation sequence and was able to fix the issue:   Here is a quick guide for getting it started from fresh: Prelimsudo apt update && sudo apt upgrade -y sudo apt install curl Dockercurl -sSL https://get.docker.com |sh Portainer (fixes exec console - don't use latest ....yet)sudo docker pull portainer/portainer-ce:2.20.3sudo docker run -d -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:2.20.3 On Saturday, August 3, 2024 at 06:07:57 AM EDT, werefkin ***@***.***> wrote: There is a bug in Docker 26 that when using Portianer 2.19 or earlier doesn't allow exec console to work. you get "unable to retrieve image details. There appears to be a fix going to 2.20.3 for Portainer, but it isn't set as "latest". The install scripts for pi-hosted only pull the "latest". Need a fix to hard set 2.20.3 during pull. re: [portainer/portainer#11436](https://github.com/portainer/portainer/issues/11436) Yes, I have also discovered this recently and was checking the current version. The update is apparently needed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Looking on your soIution, I just modified the upgrade script for ease of use
Also, as a tribute (since we're here), the pi-hosted logo has been preserved

```
#!/bin/bash

function error() {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

function check_internet() {
  printf "Checking if you are online..."
  wget -q --spider http://github.com
  if [ $? -eq 0 ]; then
    echo "Online. Continuing."
  else
    error "Offline. Go connect to the internet then run the script again."
  fi
}

check_internet

portainer_pid=`docker ps | grep portainer-ce | awk '{print $1}'`
portainer_name=`docker ps | grep portainer-ce | awk '{print $2}'`

sudo docker stop $portainer_pid || error "Failed to stop portainer!"
sudo docker rm $portainer_pid || error "Failed to remove portainer container!"
sudo docker rmi $portainer_name || error "Failed to remove/untag images from the container!"

sudo mkdir -p /portainer/Files/AppData/Config/portainer || error "Failed to create the Portainer Config Folder"

sudo docker run -d -p 9000:9000 -p 9443:9443 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /portainer/Files/AppData/Config/portainer:/data portainer/portainer-ce:2.20.3 --logo "https://pi-hosted.com/pi-hosted-logo.png" || error "Failed to run Portainer docker image!"


```

**Comment by Strobeener** [comment]
Thanks so much!!   still a total noob at linux.... gonna have to figure out how to create or update a script like this.  Thinking i just make the file and chmod to make it executable?  Did you upgrade the script on the github? And yes ... like the tribute :)

**Comment by werefkin** [comment]
> Thanks so much!! still a total noob at linux.... gonna have to figure out how to create or update a script like this. Thinking i just make the file and chmod to make it executable? Did you upgrade the script on the github? And yes ... like the tribute :)

just created an *.sh file, modified a line of the initial script, made chmod +x, executed with sudo, nothing special
also to not forget to add pi-hosted App Template..
everything seems to work
