### ISSUE TITLE
Is there special setup for Huginn in order for it to work?

### ISSUE THREAD

**Issue by jonstump** [pi-hosted/pi-hosted#26]
**Question**
Is there special setup for Huginn in order for it to work?

**Context**
I used the app template for Huginn. Then attempt to go to the port on my device and I get an error saying it failed to open the webpage.

**Comment by Macleykun** [comment]
So i took a bit of a look and i believe this edit is needed:
https://github.com/huginn/huginn/pull/2768/files

However, i noticed there's no way to use apt nor get any editors to test this theory in that docker container.
I also see that t he image hasn't been updated in 2 years:
https://hub.docker.com/r/mjysci/huginn

the amd64 one is fine however.

The only other one is: https://hub.docker.com/r/roylez/huginn
and this one also doesn't work, it complains about the database but even after touching and giving it 777 it still won't work.

Personally i advice to remove Huginn arm for the time being. Until a better docker image is created.

**Comment by Macleykun** [comment]
Pull that needs to be merged for arm support
https://github.com/huginn/huginn/pull/3180
Relevant issue in their side: https://github.com/huginn/huginn/issues/2648
