### ISSUE TITLE
Reactive-Resume - Is this tested before adding to template list?

### ISSUE THREAD

**Issue by iAmSaugata** [pi-hosted/pi-hosted#28]
**Question**
Reactive-Resume - Is this tested before adding to template list?

**Context**
This is not working, getting lot's or error, this is not 1 click install, could you please double check?

**Comment by martadinata666** [comment]
https://github.com/novaspirit/pi-hosted/pull/336 , tldr: un-usable due how application work right now.

**Comment by rmiddle** [comment]
Retired the template until someone can get it working completely.
