### ISSUE TITLE
[QUESTION] Wireguard Server crashes when attempting to deploy stack

### ISSUE THREAD

**Issue by thowsen** [pi-hosted/pi-hosted#51]
**Question**
Hi. I tried to install the wg-easy container via portainer but there's an undocumented field
`WG_DEFAULT_ADRESS` that is not in the  [video](https://www.youtube.com/watch?v=yB_jAumIxOg) nor mentioned in the [documentation of wireguard install](https://github.com/pi-hosted/pi-hosted/blob/master/docs/wireguard-install.md).

https://github.com/pi-hosted/pi-hosted/blob/a690bc321992fa6feed50f5a8cb484532274498d/template/portainer-v2-arm64.json#L6782-L6786

As a networking dummy I get an error upon deploying the stack.
```
level=info msg="failed to create network wg-easy_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network"
level=info msg=") (code=500)"
```

Any ideas on how to solve? Perhaps an update to the documentation could benefit more people.

**Comment by martadinata666** [comment]
If you deploy many container likely the docker exhausted ip pool address. You need to prune unused network, `docker network prune` or increase the docker ip pool https://theorangeone.net/posts/increase-docker-ip-space/

**Comment by thowsen** [comment]
> If you deploy many container likely the docker exhausted ip pool address. You need to prune unused network, `docker network prune` or increase the docker ip pool https://theorangeone.net/posts/increase-docker-ip-space/

Hi, I've pruned the networks but error is the same. I only have 6 containers running so I doubt the problem is due to saturation.  Do you have any other ideas? What values are expected to work?

When I run `ip route` I can see that the default 10.8.0.x is in use. But I get the same error when I try to change it to, say `10.9.0.x`.
```10.8.0.0/16 dev tun0 proto kernel scope link src 10.8.0.17```

**Comment by martadinata666** [comment]
another issue maybe the address already used, docker default bridge got the same IP as the wg-easy, so `WG_DEFAULT_ADRESS` this likely a way out to override it.

**Comment by thowsen** [comment]
> another issue maybe the address already used, docker default bridge got the same IP as the wg-easy, so `WG_DEFAULT_ADRESS` this likely a way out to override it.

I'm an idiot. I had an openvpn server active on the router.
Thank you for your time, much appreciated!
