### ISSUE TITLE
Caddy Server Issue

### ISSUE THREAD

**Issue by jimcuk** [pi-hosted/pi-hosted#67]
running the pre installation script for Caddy gives Failed to download Caddyfile file!

**Comment by Macleykun** [comment]
I tried this but got no error:

```
macley@raspberrypi:~ $ wget -qO- https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/tools/install_caddy.sh | bash
Checking if you are online...Online. Continuing.
Creating directories...
Downloading caddy config files
--2022-10-01 19:07:30--  https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/configs/Caddyfile
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 46 [text/plain]
Saving to: ‘/portainer/Files/AppData/Config/Caddy/Caddyfile’

/portainer/Files/AppData/Config/C 100%[============================================================>]      46  --.-KB/s    in 0s

2022-10-01 19:07:30 (1.30 MB/s) - ‘/portainer/Files/AppData/Config/Caddy/Caddyfile’ saved [46/46]

Setup complete. You can now install Caddy using the App Template.
macley@raspberrypi:~ $
```

Could you try again?

**Comment by jimcuk** [comment]
mmm
I now get this
Checking if you are online...Online. Continuing.
Creating directories...
Downloading caddy config files
/portainer/Files/AppData/Config/Caddy/Caddyfile: Is a directory
Failed to download Caddyfile file!

**Comment by Macleykun** [comment]
> Downloading caddy config files

so the download doesn't start at all or does it stop halfway or?

**Comment by Macleykun** [comment]
> mmm I now get this Checking if you are online...Online. Continuing. Creating directories... Downloading caddy config files /portainer/Files/AppData/Config/Caddy/Caddyfile: Is a directory Failed to download Caddyfile file!

heya, so i believe you're having issue's installing the file from here: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/configs/Caddyfile

I wanna know what happens when you do this on the terminal of the given device:
```
curl https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/configs/Caddyfile
```
Will it respond with:
```
localhost {
        respond "Hello, world!"
}
```
I'm gonna assume you're CA cert for github.com is expired, perhaps update all the packages and/or install:
```
apt install ca-certificates
``` (assuming you use a debian based distro).

**Comment by jimcuk** [comment]
Yes I get Hello world
and CA Certificates is already the newest version

**Comment by Macleykun** [comment]
> Yes I get Hello world
> and CA Certificates is already the newest version

Can you rerun it again?

**Comment by jimcuk** [comment]
Hi
Works now, Thanks

**Comment by Macleykun** [comment]
Awesome! Can ya close the issue aswell?Op 10 dec. 2022 om 06:33 heeft jimcuk ***@***.***> het volgende geschreven:﻿
Hi
Works now, Thanks
