### ISSUE TITLE
Clarify install guidelines on main page

### ISSUE THREAD

**Issue by DominoX** [pi-hosted/pi-hosted#68]
Guys, something is screwy with the install instructions on the main page of https://github.com/pi-hosted/pi-hosted (Readme.md)

First bold heading (Installation) guides user to install Docker (using install-docker.sh). So far so good … I’m in a puTTY session and no problems.

Then, next bold heading is Pi OS Buster, which talks about updating libseccomp2. I skip that because I’m running Bullseye.

Next heading … “Reboot for changes to take effect”. There, after the reboot, we run install-portainer.sh. Again, all good.

AND THEN SUDDENLY … instructions say “Click settings in the bottom left-hand corner …”

WTF :)

I’m in a puTTY session, as are most folk who are installing on a headless Pi. Where are the SETTINGS mentioned? Or even if you’re running a shell in the Pi desktop. Either way, you’re in a command shell, and the prompt to click Settings makes no sense at this point.

Seems to be a discontinuity in the instructions here.

I’m happy to help refine the installation instructions. Just guide me past this and I’ll PR a new, refined set of installation instructions.

Thanks for all you’re doing. This is fine work.

D

**Comment by martadinata666** [comment]
After install portainer, you access the portainer web and set the template, i agree maybe its not clear enough admfter deploy portainer

**Comment by rmiddle** [comment]
I will try and add a section about loggin into portainer.

**Comment by rmiddle** [comment]
Made it a little more clear although the doc does need some work on improving the install steps.
