### ISSUE TITLE
Tailscale

### ISSUE THREAD

**Issue by IqFiskMos** [pi-hosted/pi-hosted#69]
**Question**
How to make tailscale work?

**Context**
I have installed it from the template with authkey and so but i only get this message in logs for tailscale "failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)" Do anyone know how to fix this?

**Comment by the-maty** [comment]
I have the same problem, would like to see how to fix that too

**Comment by the-maty** [comment]
@IqFiskMos Found a solution with one guy on discord. Just edit your container and edit image that is being pulled from docker. 
Just tweak image from tailscale/tailscale:latest to **tailscale/tailscale:stable**
This fixed my (same) problem, hope it will help you
