### ISSUE TITLE
[ISSUE] speedtest-tracker isn't working

### ISSUE THREAD

**Issue by Bluesguy1984** [pi-hosted/pi-hosted#76]
**Question**
I just tried to install speedtest-tracker onto my new AMD64 Debian docker but it doesn't work.

>   56/123 [============>---------------]  45%
>   64/123 [==============>-------------]  52%
>   74/123 [================>-----------]  60%
>   84/123 [===================>--------]  68%
>   93/123 [=====================>------]  75%
>  102/123 [=======================>----]  82%
>  112/123 [=========================>--]  91%
>  122/123 [===========================>]  99%
>  123/123 [============================] 100%Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
> Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> Discovered Package: barryvdh/laravel-ide-helper
> Discovered Package: facade/ignition
> Discovered Package: fideloper/proxy
> Discovered Package: fruitcake/laravel-cors
> Discovered Package: henrywhitaker3/laravel-actions
> Discovered Package: laravel-notification-channels/telegram
> Discovered Package: laravel/slack-notification-channel
> Discovered Package: laravel/tinker
> Discovered Package: laravel/ui
> Discovered Package: nesbot/carbon
> Discovered Package: nunomaduro/collision
> Discovered Package: tymon/jwt-auth
> Package manifest generated successfully.
> 90 packages you are using are looking for funding.
> Use the `composer fund` command to find out more!
> Running database migrations
> Migration table created successfully.
> Migrating: 2014_10_12_000000_create_users_table
> Migrated:  2014_10_12_000000_create_users_table (654.44ms)
> Migrating: 2019_08_19_000000_create_failed_jobs_table
> Migrated:  2019_08_19_000000_create_failed_jobs_table (122.24ms)
> Migrating: 2020_04_03_104234_create_email_verifications_table
> Migrated:  2020_04_03_104234_create_email_verifications_table (122.20ms)
> Migrating: 2020_04_03_105113_create_active_sessions_table
> Migrated:  2020_04_03_105113_create_active_sessions_table (136.77ms)
> Migrating: 2020_04_08_120837_create_speedtests_table
> Migrated:  2020_04_08_120837_create_speedtests_table (122.48ms)
> Migrating: 2020_04_08_125647_create_jobs_table
> Migrated:  2020_04_08_125647_create_jobs_table (275.17ms)
> Migrating: 2020_05_18_211812_create_settings_table
> Migrated:  2020_05_18_211812_create_settings_table (492.67ms)
> Migrating: 2020_06_20_164502_update_speedtests_table
> Migrated:  2020_06_20_164502_update_speedtests_table (386.91ms)
> Migrating: 2020_06_21_171849_add_notifications_settings
> Migrated:  2020_06_21_171849_add_notifications_settings (319.14ms)
> Migrating: 2020_06_28_235331_update_speedtests_add_manual_column
> Migrated:  2020_06_28_235331_update_speedtests_add_manual_column (121.30ms)
> Migrating: 2020_07_03_095049_update_speedtest_add_failed_column
> Migrated:  2020_07_03_095049_update_speedtest_add_failed_column (123.00ms)
> Migrating: 2020_07_06_105930_add_graph_settings
> Migrated:  2020_07_06_105930_add_graph_settings (693.50ms)
> Migrating: 2020_07_07_215412_add_notification_agent_settings
> Migrated:  2020_07_07_215412_add_notification_agent_settings (281.32ms)
> Migrating: 2020_08_12_123941_add_healthchecks_settings
> Migrated:  2020_08_12_123941_add_healthchecks_settings (187.51ms)
> Migrating: 2020_08_21_133343_add_authentication_settings
> Migrated:  2020_08_21_133343_add_authentication_settings (98.74ms)
> Migrating: 2020_08_21_204656_add_conditional_notifications_settings
> Migrated:  2020_08_21_204656_add_conditional_notifications_settings (590.69ms)
> Migrating: 2020_08_28_192136_add_show_failed_tests_setting
> Migrated:  2020_08_28_192136_add_show_failed_tests_setting (103.20ms)
> Migrating: 2020_09_10_231121_add_widget_card_settings
> Migrated:  2020_09_10_231121_add_widget_card_settings (281.35ms)
> Migrating: 2020_12_19_211232_add_schedule_enabled_setting
> Migrated:  2020_12_19_211232_add_schedule_enabled_setting (94.31ms)
> Migrating: 2020_12_19_234248_add_app_name_setting
> Migrated:  2020_12_19_234248_add_app_name_setting (93.66ms)
> Migrating: 2020_12_20_001345_add_custom_healthchecks_setting
> Migrated:  2020_12_20_001345_add_custom_healthchecks_setting (173.69ms)
> Migrating: 2021_03_07_101259_add_speedtest_provider_setting
> Migrated:  2021_03_07_101259_add_speedtest_provider_setting (0.35ms)
> Migrating: 2021_03_07_121716_update_speedtest_server_settings_text
> Migrated:  2021_03_07_121716_update_speedtest_server_settings_text (94.79ms)
> Migrating: 2021_04_10_082758_add_visible_columns_setting
> Migrated:  2021_04_10_082758_add_visible_columns_setting (98.55ms)
> Migrating: 2021_04_10_102320_add_hidden_columns_setting
> Migrated:  2021_04_10_102320_add_hidden_columns_setting (145.95ms)
> Migrating: 2021_04_10_182503_add_influx_db_settings
> Migrated:  2021_04_10_182503_add_influx_db_settings (815.19ms)
> Generating app key
> Application key set successfully.
> Generating JWT secret
> jwt-auth secret [jhshpqYtAaMXhiqkTAsMk6Vsl9Xae1p2OoymdQw94YglFG22p4C1lVu2MscFJ77w] set successfully.
> Slack webhook is unset
> Telegram chat id and bot token unset
> Base path is unset
> AUTH variable not set. Disabling authentication
> Disabling authentication
> Clearing old jobs from queue
> chmod: cannot access '/config/www/app/Bin/speedtest': No such file or directory
> [cont-init.d] 50-speedtest: exited 0.
> [cont-init.d] 99-custom-files: executing... 
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-files: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> sh: /config/www/app/Bin/speedtest: not found

Can anyone help me out?

**Comment by rmiddle** [comment]
I am switching to a different branch for the AMD64 build.  It should be posted in the next 30 min.  Please let me know if you are still having problems.

Thanks
Robert M

**Comment by Bluesguy1984** [comment]
It works.  Thank you very much Robert!
