### ISSUE TITLE
AdGuardhome does not install

### ISSUE THREAD

**Issue by dpalusak** [pi-hosted/pi-hosted#93]
**Question**
AdGuardhome does not install from App Template

**Context**
Getting an Error 500 when trying to install.

**Comment by Macleykun** [comment]
Correct, it's b/c of this: https://github.com/pi-hosted/pi-hosted/pull/89
You can either:
Set the network type to host, or remove the 68 (this is where the problem lies).

**Comment by Macleykun** [comment]
This can be closed, adguard shall now install in one go withoud having to change any settings.

**Comment by Macleykun** [comment]
@dpalusak you can close the issue, it's fixed
