### ISSUE TITLE
[REQUEST] Add Citadel Email Server docker template

### ISSUE THREAD

**Issue by moneydontbuyclass** [pi-hosted/pi-hosted#94]
Hi,

I love all the container templates already added to the Pi-Hosted templates. I wondered if anyone knew how to set up an email server as a container on the Raspberry Pi. l am looking for something that will work with a 64bit OS. I cam across the Citadel email server, and they have some docker templates, but being a noob to dockers, I cant figure out how to compile this into my template.

**Comment by rmiddle** [comment]
Email Servers are pretty complex and easy to burn you if you don't know to run them.  I don't plan to add any email servers into the template.  You can install them using portainer or docker-compose however they are really complex and not something that I want to make simple to install.  Closing the request.
