### ISSUE TITLE
Searx configuration error

### ISSUE THREAD

**Issue by WoefulWrecker** [pi-hosted/pi-hosted#95]
System
Raspberry Pi 4B+
Raspberry OS 64bit
####################

I installed Dozzle very handy to say the least, anyway just checking the logs and came across and issue with SearNXG:
ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
ache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1

Providing a log, I'm not a programmer, just curious.

Thanks in advance

[SearXNG-2022-10-08T05-59-39.log](https://github.com/pi-hosted/pi-hosted/files/9738515/SearXNG-2022-10-08T05-59-39.log)

**Comment by martadinata666** [comment]
Can you please check the `uwsgi.ini` config.
`cat /portainer/Files/AppData/Config/searxng/uwsgi.ini | grep cache2`

Dit it got 
`cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1` or `cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1`

As the `cache2` line change part was last year, pretty curious which line it had.

**Comment by Redback813** [comment]
cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1

**Comment by martadinata666** [comment]
i see, tried deploy clean searxng it also spouted error non-sense yet it still working fine. what a misleading logs. should be upstream it is.

**Comment by Redback813** [comment]
Sometimes I get an error msg about Error! Engines cannot retrieve results:
startpage ( [timeout](http://raspberrypi:9017/stats?engine=startpage) 

I wonder how to change the DNS to that of my bare bone pi-hole to see if that solve that issue.

**Comment by Macleykun** [comment]
> Sometimes I get an error msg about Error! Engines cannot retrieve results: startpage ( [timeout](http://raspberrypi:9017/stats?engine=startpage)
> 
> I wonder how to change the DNS to that of my bare bone pi-hole to see if that solve that issue.

As the previous error can be safely ignored, can you try again to submit the logs of the problem your having now that the Engines cannot retrieve resulsts startpage?

You can change the DNS of the pi by following this guide:
https://pimylifeup.com/raspberry-pi-dns-settings/
