### ISSUE TITLE
[REQUEST] Network intrusion detection and prevention app

### ISSUE THREAD

**Issue by WoefulWrecker** [pi-hosted/pi-hosted#97]
**Is your feature request related to a problem? Please describe.**

Partly ! With all these great products come security concerns, no matter how well these 
developers are in the software, some creative hacker will bypass with some backdoor hack into the systems.

**Describe the solution you'd like**

A security product that can help protect both PI and the network with an intrusion detection and prevention system.

**Describe alternatives you've considered**

Something for the home user.

**Additional context**

**Comment by Macleykun** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> Partly ! With all these great products come security concerns, no matter how well these developers are in the software, some creative hacker will bypass with some backdoor hack into the systems.
> 
> **Describe the solution you'd like**
> 
> A security product that can help protect both PI and the network with an intrusion detection and prevention system.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> Something for the home user.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

This is quite a bit subjective, have you found something you want added? Then i can possibly look into it to add it.
But please make sure it has images on dockerhub (prefer it to be maintained and also from the developer themself).

**Comment by martadinata666** [comment]
IPS on docker is never gonna work, Intrusion and Prevention System must faced directly to outer network, this is not something that docker will do. Go to looking IPS on firewall will be your best bet.

**Comment by Macleykun** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> Partly ! With all these great products come security concerns, no matter how well these developers are in the software, some creative hacker will bypass with some backdoor hack into the systems.
> 
> **Describe the solution you'd like**
> 
> A security product that can help protect both PI and the network with an intrusion detection and prevention system.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> Something for the home user.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

hey what you think of this IDS in a container?
https://registry.hub.docker.com/r/jokobsk/pi.alert
Would that be sufficient for ya?
